export const CHANGE_FILTER = 'CHANGE_FILTER';
export const COUNT_LIKES = 'COUNT_LIKES';
export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';
export const FETCH_MEALS = 'FETCH_MEALS';
